### PR TITLE
Fix letters cutting in text rendering

### LINKED ISSUE #211: Fix cutting letters like "p"

### PR DESCRIPTION
**Pull request by WojciechBarczynski**
Closes #211

### CODE REVIEW

File: compositor_render/src/transformations/text_renderer.rs [hunk 1]
```diff
@@ -242,15 +250,12 @@ impl TextRendererNode {
...
                 }
             }
         }
 
-        let height = lines_count * line_height.ceil() as u32;
-        Resolution {
-            width: width as usize,
-            height: height as usize,
-        }
+        let height = (lines_count as f32 * line_height.ceil() + font_size / 4.0) as usize;
```
Comment (wkozyra95) [inline compositor_render/src/transformations/text_renderer.rs:258]: 1/4 font_size minimal value? Seems like a lot

Also maybe extract that to separate variable that have a meaningful name e.g
`let last_line_padding = font_size / 4.0`

**Review by wkozyra95 — APPROVED** [review]

File: compositor_render/src/transformations/text_renderer.rs (hunk 1 above)
Comment (WojciechBarczynski) [reply compositor_render/src/transformations/text_renderer.rs:258]: With 1/6 `j` is cut almost always, with 1/5 I didn't find the configuration that cuts `j` or `p`, but I left 1/4 as a margin of error. I'll use 1/5 and change it if we encounter problems in the future.
